baseurl = "https://jamaalroach.com/"
languageCode = "en"
title = "Jamaal Roach"
copyright = "(c) 2018 JRoach"
paginate = 3

googleAnalytics = ""
enableRobotsTXT = true

theme = "minimage"

[params]
  description = "A little bit of this...°"
  author = "Jamaal Roach"
  twitter = "jamaalroach"

[taxonomies]
  category = "categories"
  tag = "tags"



[[menu.global]]
    name = "About"
    url = "/page/about/"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
